'use client';
import {useState} from 'react';
import {Users, Radio, Clock3, ListChecks} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {NativeSelect as Select} from '@/components/ui/native-select';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Any=Record<string,any>;
const time=(n:number)=>n?new Intl.DateTimeFormat('ru-RU',{timeZone:'America/New_York',dateStyle:'short',timeStyle:'short'}).format(n):'Нет данных';
export function ControlPanel({data}:{data:Any}){
 const people=(data.people||[]).filter((p:Any)=>p.active),devices=data.devices||[],review=data.review||[];
 const online=people.filter((p:Any)=>devices.some((d:Any)=>d.person_id===p.id&&d.active&&d.state!=='offline'&&d.state!=='waiting'));
 const pending=devices.filter((d:Any)=>d.active).reduce((n:number,d:Any)=>n+(d.pending_count||0),0);
 return <section className="control-panel"><div className="section-head"><h2>Контроль команды</h2><span className="section-caption"><span className="subtle-dot"/>Состояние сейчас</span></div><div className="control-metrics"><div><Users size={18}/><strong>{people.length}</strong><span>Сотрудников</span></div><div><Radio size={18}/><strong>{online.length}</strong><span>На связи</span></div><div><Clock3 size={18}/><strong>{data.current?.length||0}</strong><span>Открытых сессий</span></div><div className={review.length||pending?'attention':''}><ListChecks size={18}/><strong>{review.length+pending}</strong><span>Событий ожидают</span></div></div><div className="control-rows">{people.map((p:Any)=>{const ds=devices.filter((d:Any)=>d.person_id===p.id&&d.active);const latest=Math.max(0,...ds.map((d:Any)=>d.last_seen));const issues=review.filter((e:Any)=>e.person_id===p.id).length;const queued=ds.reduce((n:number,d:Any)=>n+(d.pending_count||0),0);const connected=ds.some((d:Any)=>d.state==='connected');const stopped=data.tracking?.[p.id]?.paused;let label=!p.onboarded?'Анкета не заполнена':!ds.length?'Нет подключённых устройств':stopped?'Учёт остановлен':ds.some((d:Any)=>d.state==='clock')?'Ошибка часов устройства':queued?'Ожидает синхронизации':connected?'Устройство на связи':'Нет свежей связи';return <div className="control-row" key={p.id}><div><strong>{p.name}</strong><small>{latest?'Связь: '+time(latest):'Синхронизации ещё не было'}</small></div><span className={'health-label '+(connected&&!stopped?'good':'warn')}>{label}</span>{issues>0&&<small className="attention">На проверке: {issues}</small>}</div>;})}</div><p className="muted">Связь с устройством не означает работу. Время начисляется по действиям в ChatGPT; неподключённые устройства не видны системе.</p></section>;
}
export function ReviewPanel({data,act,busy}:{data:Any;act:(path:string,body:Any,success?:string)=>Promise<any>;busy:boolean}){
 const [item,setItem]=useState<Any|null>(null),[error,setError]=useState('');const review=data.review||[];
 return <><section className="review-panel"><div className="section-head"><h2>События на проверке</h2><span className="muted">Не включены в часы</span></div>{review.length?review.map((e:Any)=><article className="review-row" key={e.id}><div><strong>{data.people.find((p:Any)=>p.id===e.person_id)?.name||e.person_id}</strong><small>{time(e.at)} · {data.projects.find((p:Any)=>p.id===e.project_id)?.name||'Без проекта'}</small><p>{e.reason}</p></div><Button variant="outline" onClick={()=>{setError('');setItem(e);}}>Рассмотреть</Button></article>):<p className="muted">Сомнительных событий нет.</p>}</section><Dialog open={!!item} onOpenChange={v=>!v&&setItem(null)}><DialogContent className="dialog-surface"><DialogTitle>Проверка события</DialogTitle><DialogDescription>Подтверждение пересчитает сессии. Укажите проверенное время и причину решения.</DialogDescription>{item&&<form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const at=new Date(String(f.get('at'))).getTime();const r=await act('review',{id:item.id,action:f.get('decision'),at,reason:f.get('reason')},'Решение сохранено');if(r)setItem(null);else setError('Решение не сохранено. Проверьте время и доступ сотрудника.');}}><p>{item.reason}</p><label>Время с часовым поясом<Input name="at" defaultValue={new Date(item.at).toISOString()} required/></label><label>Причина<Input name="reason" required maxLength={500}/></label><label className="check-label"><input type="radio" name="decision" value="dismiss" defaultChecked/>Отклонить событие</label><label className="check-label"><input type="radio" name="decision" value="accept"/>Подтвердить указанное время</label>{error&&<p className="error" role="alert">{error}</p>}<Button disabled={busy}>Сохранить решение</Button></form>}</DialogContent></Dialog></>;
}
export function BackupPanel({data,act,busy}:{data:Any;act:(path:string,body:Any,success?:string)=>Promise<any>;busy:boolean}){
 return <section className="backup-panel"><div className="section-head"><h2>Резервные копии</h2><Button variant="outline" disabled={busy} onClick={()=>act('backup',{},'Копия создана и проверена чтением')}>Создать копию</Button></div><p className="muted">Автоматическая копия создаётся при синхронизации устройств, если с предыдущей прошли сутки. В дни без подключённых устройств используйте ручную копию.</p>{data.backupError&&<p className="error">{data.backupError}</p>}{(data.backups||[]).map((b:Any)=><div className="backup-row" key={b.id}><div><strong>{time(b.created)}</strong><small>{Math.ceil(b.bytes/1024)} КБ · {b.verified?'Проверена':'Не проверена'}</small></div>{data.me.role==='owner'&&<Button asChild variant="outline"><a href={'/api/backup/download?id='+encodeURIComponent(b.id)}>Скачать</a></Button>}</div>)}{!data.backups?.length&&<p className="muted">Резервных копий пока нет.</p>}</section>;
}

export function ManualEntry({data,act,busy}:{data:Any;act:(path:string,body:Any,success?:string)=>Promise<any>;busy:boolean}){
 const [open,setOpen]=useState(false),[error,setError]=useState('');
 return <><Button variant="outline" onClick={()=>{setError('');setOpen(true);}}>Добавить время вручную</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="dialog-surface"><DialogTitle>Ручная запись времени</DialogTitle><DialogDescription>Для пропущенного интервала или старой истории. Причина и автор сохранятся в журнале.</DialogDescription><form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const r=await act('manual',{...f,start:Date.parse(String(f.start)),end:Date.parse(String(f.end))},'Интервал добавлен');if(r)setOpen(false);else setError('Запись не сохранена. Проверьте время: пересечения запрещены.');}}><label>Сотрудник<Select name="personId">{data.people.map((p:Any)=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></label><label>Проект<Select name="projectId">{data.projects.map((p:Any)=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></label><label>Начало с часовым поясом<Input name="start" placeholder="2026-09-30T09:00:00-04:00" required/></label><label>Конец с часовым поясом<Input name="end" placeholder="2026-09-30T10:00:00-04:00" required/></label><label>Причина<Input name="reason" required maxLength={500}/></label>{error&&<p className="error" role="alert">{error}</p>}<Button disabled={busy}>Добавить интервал</Button></form></DialogContent></Dialog></>;
}
