import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import {webcrypto} from 'node:crypto';
function extension(overrides={},responder){let handler;const data={binding:{id:'d',personId:'zafar',name:'Зафар'},clockCheckedAt:Date.now(),lastSync:Date.now(),...overrides};const calls=[];const chrome={storage:{local:{get:async defaults=>({...structuredClone(defaults),...structuredClone(data)}),set:async values=>Object.assign(data,structuredClone(values))}},alarms:{create(){},onAlarm:{addListener(){}}},runtime:{id:'extension',onMessage:{addListener(fn){handler=fn;}}},tabs:{query:async()=>[{id:1}],sendMessage:async(id,msg)=>{calls.push(msg);if(responder)return responder(msg);if(msg.path.startsWith('extension-state'))return {ok:true,data:{me:{id:'zafar',onboarded:1},serverTime:Date.now(),paused:false,projects:[{id:'homekept'}]}};return {ok:true,data:{accepted:(msg.body?.events||[]).map(e=>e.id),serverTime:Date.now(),paused:false}};}}};vm.runInContext(fs.readFileSync('public/extension/background.js','utf8'),vm.createContext({chrome,crypto:webcrypto,Date,console,encodeURIComponent}));return {data,calls,call:(msg,sender={id:'extension'})=>new Promise(resolve=>handler(msg,sender,resolve))};}
const activity=()=>({type:'activity',at:Date.now(),context:'chat-a'});
const sender={id:'extension',tab:{url:'https://chatgpt.com/c/a'}};
test('A rejected clock check blocks subsequent activity',async()=>{const x=extension({},msg=>({ok:true,data:{me:{id:'zafar'},serverTime:Date.now()+300000,paused:false,projects:[]}}));await x.call({type:'sync'});assert.equal(x.data.clockBlocked,true);await x.call(activity(),sender);assert.equal((x.data.queue||[]).length,0);assert.equal(x.calls.at(-1).body.status,'clock');});
test('Employee switch blocks collection and preserves the old queue',async()=>{const old={id:'old',personId:'zafar',deviceId:'d'};const x=extension({queue:[old]},()=>({ok:true,data:{me:{id:'daniil'},serverTime:Date.now()}}));await x.call({type:'sync'});assert.equal(x.data.authBlocked,true);await x.call(activity(),sender);assert.equal(x.data.queue.length,1);assert.equal(x.data.queue[0].personId,'zafar');});
test('Offline manual stop takes effect immediately, survives storage and awaits server sync',async()=>{const x=extension({},()=>{throw new Error('Offline');});await x.call({type:'tracking',action:'stop'});assert.equal(x.data.paused,true);assert.ok(x.data.pendingStop);await x.call(activity(),sender);assert.equal((x.data.queue||[]).length,0);});
test('Sequence numbers persist and unrelated web pages cannot issue control commands',async()=>{const x=extension();await x.call(activity(),sender);await x.call(activity(),sender);assert.equal(x.data.queue.length,2);assert.deepEqual(x.data.queue.map(e=>e.seq),[1,2]);assert.equal(x.data.nextSeq,3);await x.call({type:'tracking',action:'stop'},sender);assert.equal(x.data.paused,undefined);await x.call(activity(),{id:'extension',tab:{url:'https://example.com/'}});assert.equal(x.data.queue.length,2);});
test('Reconnect of a valid binding retains identity instead of creating a replacement device',async()=>{const x=extension();await x.call({type:'connect'});assert.equal(x.data.binding.id,'d');assert.equal(x.calls.some(c=>c.path==='devices'),false);});
test('Context mapping propagates only inside the same recognized project',async()=>{const x=extension({projectMaps:{project:'homekept'}});await x.call({...activity(),projectContext:'project'},sender);await x.call({...activity(),context:'another-chat',projectContext:'unknown'},sender);assert.deepEqual(x.data.queue.map(e=>e.projectId),['homekept','none']);});
